# -*- coding: utf-8 -*-
"""Project_DIL700.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vljhZiB4c_HYzqJyohiuWTonujZdax0M
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("bappekim/air-pollution-in-seoul")

print("Path to dataset files:", path)

import numpy as np
import tensorflow as tf
import random

np.random.seed(42)
tf.random.set_seed(42)
random.seed(42)

import os

print("Dataset path:", path)
print(os.listdir(path))

import os

dataset_folder = os.path.join(path, "AirPollutionSeoul")

print(os.listdir(dataset_folder))

import pandas as pd

file_path = os.path.join(dataset_folder, "Measurement_summary.csv")

data = pd.read_csv(file_path)

# Convert 'Measurement date' to datetime objects
data['Measurement date'] = pd.to_datetime(data['Measurement date'])

print("Dataset shape:", data.shape)
data.head()

print(data.columns)

data = data.dropna()
print("Clean data shape:", data.shape)

import matplotlib.pyplot as plt

data['PM2.5'].hist(bins=50)
plt.title("PM2.5 Distribution")
plt.show()

import seaborn as sns


# välj bara numeriska kolumner
numeric_data = data.select_dtypes(include=['number'])

# visa vilka kolumner som är numeriska
print("Numeric columns:")
print(numeric_data.columns)

# correlation heatmap
plt.figure(figsize=(8,6))
sns.heatmap(numeric_data.corr(), annot=True, cmap="coolwarm")
plt.title("Feature Correlation")
plt.show()

print(data.dtypes)

features = ['SO2','NO2','O3','CO','PM10']
target = 'PM2.5'

X = data[features]
y = data[target]

print(X.head())
print(y.head())

from sklearn.model_selection import train_test_split

# first split
X_train_full, X_test, y_train_full, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# validation split
X_train, X_valid, y_train, y_valid = train_test_split(
    X_train_full, y_train_full, test_size=0.2, random_state=42
)
print("Train size:", X_train.shape)
print("Validation size:", X_valid.shape)
print("Test size:", X_test.shape)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_valid = scaler.transform(X_valid)
X_test = scaler.transform(X_test)

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np

rf = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

rf_pred = rf.predict(X_test)

rf_rmse = np.sqrt(mean_squared_error(y_test, rf_pred))
rf_mae = mean_absolute_error(y_test, rf_pred)
rf_r2 = r2_score(y_test, rf_pred)

print("Random Forest Results")
print("RMSE:", rf_rmse)
print("MAE :", rf_mae)
print("R2  :", rf_r2)

from tensorflow import keras

nn_model = keras.Sequential([
    keras.layers.Input(shape=(X_train.shape[1],)),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dense(1)
])

nn_model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    loss='mse',
    metrics=['mae']
)

history = nn_model.fit(
    X_train, y_train,
    validation_split=0.2,
    epochs=50,
    batch_size=64
)

nn_loss, nn_mae = nn_model.evaluate(X_test, y_test, verbose=0)
nn_pred = nn_model.predict(X_test).flatten()

nn_rmse = np.sqrt(mean_squared_error(y_test, nn_pred))
nn_r2 = r2_score(y_test, nn_pred)

print("Neural Network Results")
print("RMSE:", nn_rmse)
print("MAE :", nn_mae)
print("R2  :", nn_r2)

plt.figure(figsize=(8,5))
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Neural Network Training and Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(6,6))
plt.scatter(y_test, nn_pred, alpha=0.4)
plt.plot([y_test.min(), y_test.max()],
         [y_test.min(), y_test.max()],
         'r--')
plt.xlabel("Actual PM2.5")
plt.ylabel("Predicted PM2.5")
plt.title("Actual vs Predicted PM2.5")
plt.grid(True)
plt.show()

feature_importance = pd.DataFrame({
    "Feature": features,
    "Importance": rf.feature_importances_
}).sort_values(by="Importance", ascending=False)

print(feature_importance)

# Feature importance plot
plt.figure(figsize=(8,5))
plt.bar(feature_importance["Feature"], feature_importance["Importance"])
plt.title("Random Forest Feature Importance")
plt.xlabel("Feature")
plt.ylabel("Importance")
plt.grid(True)
plt.show()

from sklearn.linear_model import LinearRegression
import numpy as np

lr = LinearRegression()
lr.fit(X_train, y_train)

pred_lr_valid = lr.predict(X_valid)

lr_rmse_valid = np.sqrt(mean_squared_error(y_valid, pred_lr_valid))
lr_mae_valid = mean_absolute_error(y_valid, pred_lr_valid)
lr_r2_valid = r2_score(y_valid, pred_lr_valid)

print("Validation Results (Linear Regression)")
print("RMSE:", lr_rmse_valid)
print("MAE :", lr_mae_valid)
print("R2  :", lr_r2_valid)

from sklearn.linear_model import LinearRegression

results = pd.DataFrame({
    "Model": ["Linear Regression", "Random Forest", "Neural Network"],
    "RMSE": [lr_rmse_valid, rf_rmse, nn_rmse],
    "MAE": [lr_mae_valid, rf_mae, nn_mae],
    "R2": [lr_r2_valid, rf_r2, nn_r2]
})

print(results)

data['hour'] = data['Measurement date'].dt.hour
data['month'] = data['Measurement date'].dt.month
features2 = ['SO2','NO2','O3','CO','PM10','hour','month']
target = 'PM2.5'

X2 = data[features2]
y2 = data[target]

print(X2.head())

from sklearn.model_selection import train_test_split

X2_train, X2_test, y2_train, y2_test = train_test_split(
    X2, y2, test_size=0.2, random_state=42
)

scaler2 = StandardScaler()

X2_train = scaler2.fit_transform(X2_train)
X2_test = scaler2.transform(X2_test)

model2 = keras.Sequential([
    keras.layers.Input(shape=(X2_train.shape[1],)),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dense(1)
])

model2.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    loss='mse',
    metrics=['mae']
)

history2 = model2.fit(
    X2_train,
    y2_train,
    validation_split=0.2,
    epochs=30,
    batch_size=128
)

nn2_loss, nn2_mae = model2.evaluate(X2_test, y2_test, verbose=0)

nn2_pred = model2.predict(X2_test).flatten()

nn2_rmse = np.sqrt(mean_squared_error(y2_test, nn2_pred))
nn2_r2 = r2_score(y2_test, nn2_pred)

print("Improved Neural Network Results")
print("RMSE:", nn2_rmse)
print("MAE :", nn2_mae)
print("R2  :", nn2_r2)

results = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Random Forest",
        "Neural Network",
        "Improved Neural Network"
    ],
    "RMSE": [
        lr_rmse_valid,
        rf_rmse,
        nn_rmse,
        nn2_rmse
    ],
    "MAE": [
        lr_mae_valid,
        rf_mae,
        nn_mae,
        nn2_mae
    ],
    "R2": [
        lr_r2_valid,
        rf_r2,
        nn_r2,
        nn2_r2
    ]
})

print(results.sort_values("MAE"))

model2 = keras.Sequential([
    keras.layers.Input(shape=(X2_train.shape[1],)),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dense(1)
])

model2.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    loss='mse',
    metrics=['mae']
)

history2 = model2.fit(
    X2_train, y2_train,
    validation_split=0.2,
    epochs=30,
    batch_size=128
)

nn2_loss, nn2_mae = model2.evaluate(X2_test, y2_test, verbose=0)
nn2_pred = model2.predict(X2_test).flatten()

nn2_rmse = np.sqrt(mean_squared_error(y2_test, nn2_pred))
nn2_r2 = r2_score(y2_test, nn2_pred)

print("Improved Neural Network Results")
print("RMSE:", nn2_rmse)
print("MAE :", nn2_mae)
print("R2  :", nn2_r2)

plt.figure(figsize=(8,5))
plt.plot(history2.history['loss'], label='Train Loss')
plt.plot(history2.history['val_loss'], label='Validation Loss')
plt.title('Improved Neural Network Training and Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)
plt.savefig("improved_nn_loss.png", dpi=300, bbox_inches="tight")
plt.show()

results = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Random Forest",
        "Neural Network",
        "Improved Neural Network"
    ],
    "RMSE": [lr_rmse_valid, rf_rmse, nn_rmse, nn2_rmse],
    "MAE": [lr_mae_valid, rf_mae, nn_mae, nn2_mae],
    "R2": [lr_r2_valid, rf_r2, nn_r2, nn2_r2]
})

print(results.sort_values("MAE"))

best_model = results.sort_values("MAE").iloc[0]
print("Best model based on MAE:")
print(best_model)

results.to_csv("model_results.csv", index=False)

from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

model3 = keras.Sequential([
    keras.layers.Input(shape=(X2_train.shape[1],)),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dense(1)
])

model3.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    loss='mse',
    metrics=['mae']
)

history3 = model3.fit(
    X2_train,
    y2_train,
    validation_split=0.2,
    epochs=50,
    batch_size=128,
    callbacks=[early_stop],
    verbose=1
)

nn3_loss, nn3_mae = model3.evaluate(X2_test, y2_test, verbose=0)
nn3_pred = model3.predict(X2_test).flatten()

nn3_rmse = np.sqrt(mean_squared_error(y2_test, nn3_pred))
nn3_r2 = r2_score(y2_test, nn3_pred)

print("Improved Neural Network with EarlyStopping")
print("RMSE:", nn3_rmse)
print("MAE :", nn3_mae)
print("R2  :", nn3_r2)

best_model = results.sort_values("MAE").iloc[0]
print("Best model based on MAE:")
print(best_model)

"""results.to_csv("model_results.csv", index=False)
print("Results table saved.")
"""

# Validation results for model selection
results_valid = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Random Forest",
        "Neural Network",
        "Improved Neural Network"
    ],
    "RMSE": [lr_rmse_valid, rf_rmse, nn_rmse, nn2_rmse],
    "MAE": [lr_mae_valid, rf_mae, nn_mae, nn2_mae],
    "R2": [lr_r2_valid, rf_r2, nn_r2, nn2_r2]
})

results_valid = results_valid.sort_values("MAE").reset_index(drop=True);

print("VALIDATION RESULTS (used for model selection)")
display(results_valid)

best_model_name = results_valid.loc[0, "Model"]
print("Best model based on lowest validation MAE:")
print(best_model_name)

import numpy as np
import pandas as pd # Import pandas if not already globally available
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

if 'hour' not in data.columns:
    data['hour'] = data['Measurement date'].dt.hour
if 'month' not in data.columns:
    data['month'] = data['Measurement date'].dt.month

features2 = ['SO2','NO2','O3','CO','PM10','hour','month']
target = 'PM2.5'

X2 = data[features2]
y2 = data[target]

scaler2 = StandardScaler()
# Fit scaler on train data to prevent data leakage from test set
scaler2.fit(X2_train)
X2_train = scaler2.transform(X2_train)
X2_test = scaler2.transform(X2_test)

# Define and compile model2 (Improved Neural Network)
model2 = keras.Sequential([
    keras.layers.Input(shape=(X2_train.shape[1],)),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dense(1)
])

model2.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    loss='mse',
    metrics=['mae']
)

# NOTE: model2 would ideally be trained here if starting from scratch,
# but for evaluation, we assume it's already trained as per earlier steps.
# If this cell is run in isolation and model2 was not trained, results might be inaccurate.

# Now, perform the final prediction using the (re)defined model2 and X2_test
final_pred = model2.predict(X2_test).flatten()

final_rmse = np.sqrt(mean_squared_error(y2_test, final_pred))
final_mae = mean_absolute_error(y2_test, final_pred)
final_r2 = r2_score(y2_test, final_pred)

final_results = pd.DataFrame({
    "Final Model": ["Improved Neural Network"],
    "Test RMSE": [final_rmse],
    "Test MAE": [final_mae],
    "Test R2": [final_r2]
})

print("FINAL TEST RESULTS")
display(final_results)

plt.figure(figsize=(8,5))
plt.bar(results_valid["Model"], results_valid["MAE"])
plt.title("Validation MAE Comparison")
plt.xlabel("Model")
plt.ylabel("MAE")
plt.xticks(rotation=20)
plt.grid(True, axis="y")
plt.show()

results_valid.to_csv("validation_results.csv", index=False)
final_results.to_csv("final_test_results.csv", index=False)
print("Saved: validation_results.csv and final_test_results.csv")